### ISSUE TITLE
Spec documents missing?

### ISSUE THREAD

**Issue by PaintNinja** [multiformats/specs#3]
The repository appears to be empty aside from the license and readme.

**Comment by fabianhjr** [comment]
Specs of each component are in their own repos.

It might be interesting to add each of those spec repos as git submodules. BRB Making a PR.

**Comment by daviddias** [comment]
@fabianhjr is correct. The specs can be found at:

- github.com:multiformats/multibase
- github.com:multiformats/multihash
- github.com:multiformats/multiaddr
- github.com:multiformats/multicodec
- github.com:multiformats/multigram
- github.com:multiformats/cid

This repo lost its purpose as we decided to have its spec in their repo instead of merging all of them. I'm going to archive this repo.
